name: Publish Docker Image DockerHub
on:
  push:
    branches:
      - main
jobs:
  publish_to_registries:
    name: Push Docker image to DockerHub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Log in DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to DH
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: wallacepf/kvpassrotate:latest