name: Publish Docker Image GitHub
on:
  push:
    branches:
      - main
jobs:
  publish_to_registries:
    name: Push Docker image to GitHub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Login GitHub Reg
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: docker.pkg.github.com/${{ github.repository }}/kvpassrotate:latest
  
